### PR TITLE
fix base case of showing the root path

### PR DESCRIPTION
**Pull request by gregwebs**

### CODE REVIEW

**Comment by domdere** [comment]
Thanks!

**Comment by domdere** [comment]
Hmm I can't check the merge conflicts on the command line at the moment, does this need to be rebased?

**Comment by gregwebs** [comment]
I just rebased it

**Comment by gregwebs** [comment]
This was sitting around against an older version. I added in the usage of `PathSegment` now so the change is pretty simple, but untested against this latest master now.

**Pull request merged**
